spring:
  application:
    name: kafapi

server:
  port : 8010

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    export:
      statsd:
        host: 192.168.0.38
        port: 8125

kafka:
  topicName: messages
  bootstrapServers: http://192.168.0.38:9092
  applicationId: app-appid-1
  applicationServerHost: ${MY_POD_IP:localhost}
  applicationServerPort: 8010
  storeName: key-value-store
  adminClientId: admin-clientid-1